
import java.io.File;
import java.io.IOException;
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 242353497
 */
public class MainProgram extends javax.swing.JFrame {
    int easyCount = 0;
    int midCount = 0;
    int hardCount = 0;
    Easy [] easyQuestions = new Easy[10];
    mid [] midQuestions = new mid[10];
    Hard [] hardQuestions = new Hard[10];
    /**
     * Creates new form NewJFrame
     */
    public MainProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fake = new javax.swing.JButton();
        real = new javax.swing.JButton();
        header = new javax.swing.JTextField();
        nextEasy = new javax.swing.JButton();
        nextMid = new javax.swing.JButton();
        nextHard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fake.setBackground(new java.awt.Color(255, 0, 51));
        fake.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fake.setText("Fake");
        fake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakeActionPerformed(evt);
            }
        });

        real.setBackground(new java.awt.Color(0, 255, 51));
        real.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        real.setText("Real");
        real.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realActionPerformed(evt);
            }
        });

        header.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        header.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headerActionPerformed(evt);
            }
        });

        nextEasy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nextEasy.setText("Next Easy");
        nextEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextEasyActionPerformed(evt);
            }
        });

        nextMid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nextMid.setText("Next Mid");
        nextMid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMidActionPerformed(evt);
            }
        });

        nextHard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nextHard.setText("Next Hard");
        nextHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextHardActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Points");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Question");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(fake, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174)
                .addComponent(real, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(nextEasy)
                .addGap(142, 142, 142)
                .addComponent(nextMid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(nextHard)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(real, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fake, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextMid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextHard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextEasy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fakeActionPerformed

    private void headerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headerActionPerformed

    private void realActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realActionPerformed

    private void nextEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextEasyActionPerformed
        int lines = countLines("easy");
        String [] easyQ = take(lines, "easy");
        String [] easyA = take(lines, "easyAns");
        int [] easyAnswers = new int [easyA.length];
        boolean [] bool = new boolean [easyA.length];
        for (int i = 0; i < easyAnswers.length;i++){
            easyAnswers[i] = Integer.parseInt(easyA[i]);
            if(easyAnswers[0] == 0){
                bool[i] = true;
            } else {
                bool[i] = false;
            }
        }
        for (int i = 0; i<easyQ.length;i++){
            Answers answer = new Answers(bool[i]);
            easyQuestions[i] = new Easy(answer, (i + 1), easyQ[i]);
        }
        header.setText(easyQuestions[easyCount].getQuestion());
    }//GEN-LAST:event_nextEasyActionPerformed

    private void nextMidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextMidActionPerformed

    }//GEN-LAST:event_nextMidActionPerformed

    private void nextHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextHardActionPerformed

    }//GEN-LAST:event_nextHardActionPerformed

    /**
     * Counts line in file
     * @return lineCount
     */
    private int countLines(String filename){
        // Declare Variables
        int lineCount = 0;
        // Try catch
        try {
            // Loop through data.txt if there is a next line
            Scanner fileInput = new Scanner(new File(filename));
            while (fileInput.hasNextLine()){
                fileInput.nextLine();
                lineCount++; // Add one to counter 
            }
            fileInput.close(); // Close scanner
            
        } catch(IOException e){
            System.out.print("Java Exception" + e);
        }
        return lineCount; // Return lineCount
    }
    /**
     * Take questions from file
     * @param lineCount This creates the array size
     * @return questions This holds the questions in an array
     */
    private String [] take(int lineCount, String filename){
        // Declare Variables
        int count = 0;
        String [] Q = new String [lineCount];
        // Try catch
         try{
             // Loop through data.txt and store questions
            Scanner fileInput = new Scanner(new File(filename));
            while(fileInput.hasNext()){
                String output = fileInput.nextLine();
                // Store values
                Q[count] = output;
                count++; // Add to counter
            }
        } catch (IOException e){
            System.err.println("Java Exception: " + e);
        } catch (StringIndexOutOfBoundsException p) {
            System.err.println("Java Exception: " + p);
        }

        return Q; // Return array
    }

    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fake;
    private javax.swing.JTextField header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nextEasy;
    private javax.swing.JButton nextHard;
    private javax.swing.JButton nextMid;
    private javax.swing.JButton real;
    // End of variables declaration//GEN-END:variables
}
